version: '3.8'

services:
  db:
    image: postgres:14
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
      POSTGRES_DB: memes_db
    volumes:
      - postgres_data:/var/lib/postgresql/data
    ports:
      - "5433:5432"

  minio:
    image: minio/minio
    environment:
      MINIO_ROOT_USER: minioadmin
      MINIO_ROOT_PASSWORD: minioadmin
    volumes:
      - minio_data:/data
    command: server /data
    ports:
      - "9000:9000"

  api:
    image: python:3.11-slim
    depends_on:
      - db
      - minio
    ports:
      - "8000:8000"
    environment:
      DATABASE_URL: postgres://user:password@db/memes_db
      MINIO_ENDPOINT: http://minio:9000
      MINIO_ACCESS_KEY: minioadmin
      MINIO_SECRET_KEY: minioadmin
      MINIO_BUCKET_NAME: memes
    volumes:
      - ./api:/app
    command: >
      sh -c "pip install --no-cache-dir -r /app/requirements.txt &&
             uvicorn /app/main:app --host 0.0.0.0 --port 8000"
    
  media_service:
    image: python:3.11-slim
    depends_on:
      - minio
    ports:
      - "8001:8001"
    environment:
      MINIO_ENDPOINT: http://minio:9000
      MINIO_ACCESS_KEY: minioadmin
      MINIO_SECRET_KEY: minioadmin
      MINIO_BUCKET_NAME: memes
    volumes:
      - ./media_service:/app
    command: >
      sh -c "pip install --no-cache-dir -r /app/requirements.txt &&
             uvicorn /app/main:app --host 0.0.0.0 --port 8001"

volumes:
  postgres_data:
  minio_data:
